# Generated by Gemini 3.1

from gguf import GGUFReader
import numpy as np

def dequantize_q8_0(raw_data):
    """
    Dequantize a Q8_0 row (token embedding).
    Layout: [f16 delta (2 bytes)][32 x int8 (32 bytes)] = 34 bytes per block.
    """
    # Q8_0 uses 32-element blocks
    block_size = 32
    bytes_per_block = 34
    num_blocks = len(raw_data) // bytes_per_block
    
    # Initialize the float array
    floats = np.zeros(num_blocks * block_size, dtype=np.float32)
    
    for i in range(num_blocks):
        start = i * bytes_per_block
        # 1. Get the scale (delta) from the first 2 bytes of the block
        delta = np.frombuffer(raw_data[start : start + 2], dtype=np.float16)[0]
        
        # 2. Get the 32 quantized int8 values
        qs = raw_data[start + 2 : start + 34].view(np.int8)
        
        # 3. Dequantize: value = quantized_weight * scale
        floats[i * block_size : (i + 1) * block_size] = qs.astype(np.float32) * delta
        
    return floats

model_path = "gemma-4-e2b-it-Q8_0.gguf"
reader = GGUFReader(model_path)

# Tensors are stored in a list; we can find the one we need by its name attribute
tensor_name = "token_embd.weight" 
target_tensor = None

for tensor in reader.tensors:
    if tensor.name == tensor_name:
        target_tensor = tensor
        break

if target_tensor is None:
    # Print all names to help you find the correct one if 'token_embd.weight' is wrong
    available = [t.name for t in reader.tensors]
    print(f"Tensor '{tensor_name}' not found. Available: {available}")
else:
    # token_id is the index of the token in the vocabulary
    token_id = 2  
    
    # .data provides a memory-mapped NumPy array of the tensor weights
    embedding = target_tensor.data[token_id]
    
    print(f"Embedding for token {token_id} (shape {embedding.shape}):")
    print(embedding)

    embedding_floats = dequantize_q8_0(embedding)
    print(embedding_floats)
